apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-dua
spec:
  selector:
    matchLabels:
      app: goapp-dua
  template:
    metadata:
      labels:
        app: goapp-dua
    spec:
      containers:
      - name: goapp-dua
        image: asia.gcr.io/studidevops-369306/goapp:3
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: gcr-credentials