apiVersion: kustomize.config.k8s.io/v1beta1
namespace: ingress
kind: Kustomization
resources:
  - namespace.yaml
  - ../../../../helm/ingress-nginx/repository.yaml
  - ingress
  - cert-manager
  - demo-adhithia-me.yaml